apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: cf9fg1x2v-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/cf9fg1x2v-dotnet-basic-gitops